spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-3.5-turbo
      temperature: 0.7
      max-tokens: 1000

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: SPRING_AI_CHAT_MEMORY
            max-messages: 10
            schema-location: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-mysql.sql

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.springaiopenai: DEBUG
    org.springframework.ai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
